#!/usr/bin/perl
#use strict;
#use warnings;
use Path::Class;
use autodie;

 my $dir = dir("/Users/rich/cmpe209_dos_project");
 my $file = $dir->file("withcookie.txt");
 my $filename = 'report_1.txt';
 open(my $fh, '>', $filename) or die "Could not open file '$filename' $!";
#print $fh "My first report generated by perl\n";
 # my $content = $file->slurp();

 # openr() returns an IO::File object to read from
 my $file_handle = $file->openr();
 my $newcon = 0;
 my @start,@finish;
 # Read in line at a time
 my $line = $file_handle->getline();
 while($line){

 if($line=~/Flags \[S\]/){
        if($newcon == 1){
#               print "timeout connection ";
                print $fh ($start[1]*60 + $start[2]);
                print $fh "\.";
                print $fh  $start[3];
                print $fh "\t200\n";
        }
        @start = split(/:|\.|IP/,$line);
        $newcon = 1;
        $line = $file_handle->getline();

        if($line=~/Flags \[S\.\]/){
                $line = $file_handle->getline();
                while( (!($line=~/Flags \[F\.\]/) )&&(!($line=~/Flags \[R\]/)) ){
                        $line = $file_handle->getline();
                }
                if($line=~/Flags \[R\]/){
                        @finish = split(/:|\.|IP/,$line);
                        $newcon = 0;
                        print $fh ($start[1]*60 + $start[2]);
                        print $fh "\.";
                        print $fh $start[3];
   print $fh "\t0\.";
                        print $fh ( (($finish[1]*60 - $start[1]*60) + ($finish[2] - $start[2]) )*1000000 + ($finish[3]-$start[3]) );
                        print $fh "\n";
                        $line = $file_handle->getline();
                }elsif($line=~/Flags \[F\.\]/){
                $line = $file_handle->getline();
                        @finish = split(/:|\.|IP/,$line);
                        $newcon = 0;
#                       print "normal  connection ";
                        print $fh ($start[1]*60 + $start[2]);
                        print $fh "\.";
                        print $fh $start[3];
                        print $fh "\t0\.";
                        print $fh ( (($finish[1]*60 - $start[1]*60) + ($finish[2] - $start[2]) )*1000000 + ($finish[3]-$start[3]) );
                        print $fh "\n";
                        $line = $file_handle->getline();
                }
        }

 }else{$line = $file_handle->getline();}


}

close $fh;


                                                                                                                                                                 71,0-1        Bot
